version: '2'
services:
  level00:
    build: ./0
    env_file: ./env/level00
  level01:
    build: ./1
    env_file: ./env/level01
  level02:
    build: ./2
    env_file: ./env/level02
  level03:
    build: ./3
    env_file: ./env/level03
  portal:
    build: ./
    volumes:
      - ./env:/app/env
    ports:
      - 80:80
